### ISSUE TITLE
Move the generated bindings in separate project

### ISSUE THREAD

**Issue by yyoncho** [emacs-ng/emacs-ng#20]
The generated bindings are 6mb file and they pretty much kill all the IDE tools and `cargo check` (e. g. each change triggers recompilation of the bindings).  This PR is POC https://github.com/emacs-ng/emacs-ng/pull/12 and proves that it can be done. Ideally, no other code except the bindings should be in that project.

**Comment by brotzeit** [comment]
The problem here is that we end up with cyclic dependencies(with the lisp crate) when we move the generated bindings in a seperate crate while using `LispObject` in the bindings crate. 

My first thought is that we use `Lisp_Object` instead. But we then would have to perform `obj.into()` in each call of generated functions. Do we want that ? Are there any other possible solutions ?

**Comment by appetrosyan** [comment]
```
obj.into()
```
is a small price to pay for the improved compilation times. And we can make use of `as_ref` in most cases to elide the need for conversions. From the point of view of decoupling it might even be preferable to avoid a circular dependency by opacifying the object.

**Comment by declantsien** [comment]
I guess the name of this separate project would be `emacs-sys`,
like the `gtk-sys`, 'llvm-sys', which provides bindings to Emacs's C API.
And some Rust traits for those function/macros defined in C header files.

The generated bindings is in Cargo `OUT_DIR`, since rust-analyzer now
supports jumping to file in `OUT_DIR`.

We put this crate inside the source tree instead of a separate project.
