### ISSUE TITLE
[Features Request] Prebuilt Binaries for macOS 

### ISSUE THREAD

**Issue by shaunsingh** [emacs-ng/emacs-ng#323]
Hi, I prefer to have a portable configuration that can be installed via a script. Emacs-ng is often a pain to build, especially on slower machines. In the future would you consider adding a prebuilt binary for macOS alongside the .deb packages for linux?

Ideally this would also include native-comp, but I understand thats a pain to configure on macOS so its fine if its excluded.

**Comment by declantsien** [comment]
Prebuilt Binaries for macOS can be found [emacsng-darwin-builds](https://github.com/emacs-ng/emacsng-darwin-builds).
There are two profile.
- Default
Since we have disabled JavaScript for now. There shouldn't be much difference with upstream GNU Emacs master.
- Webrender
Build with experimental Webrender
