### ISSUE TITLE
Make emacs's internel more multi-threaded and user's editing flow smoother

### ISSUE THREAD

**Issue by harryfei** [emacs-ng/emacs-ng#378]
Some heavy tasks in emacs tends to block user's editing flow. We could rewrite key functions of those tasks in a multi-thread manner.

We can collect the top-blocking things in this issue and discuss the proper solution to optimize them.

**Comment by black7375** [comment]
1. You're right. That's why I'm linking to the issue and not the RFC.
  If we want to use Rope we have to use [regex-automata](https://github.com/BurntSushi/regex-automata).
  - [execute a regex on text streams issue](https://github.com/rust-lang/regex/issues/425)
  -  [Alacritty Sample](https://github.com/alacritty/alacritty/blob/96ea5c445ecc25a5b2d400b11f0ff843e9cbdd7a/alacritty_terminal/src/term/search.rs#L198-L283)
2. Here is the [benchmark code for ropey](https://github.com/cessen/ropey/tree/master/benches).
  There is no direct benchmark, but I expect the following differences in structure.
  - Gap buffer: Very light and fast for small files(kb). It is [not good for multi-cursor](https://nullprogram.com/blog/2017/09/07/) because the gap position changes depending on the cursor position.
  - Rope: Fast for relatively large files(MB), and decent performance even in the worst case. But inefficient when files and edits are small.
  As mentioned earlier, support for async is relatively easy. ([roepy issue](https://github.com/cessen/ropey/issues/34#issuecomment-812996987), [xi-editor README](https://github.com/xi-editor/xi-editor#design-decisions))

**Comment by harryfei** [comment]
> Rope: Fast for relatively large files(MB), and decent performance even in the worst case. But inefficient when files and edits are small.

But code source tends to small

**Comment by black7375** [comment]
Yeah. it's a trade-off.
The disclaimer is that rope's easy to implement asynchronously, and on a small scale it's hard for humans to notice that it's slow.  https://josephg.com/ropereport/ropes/ropey/1000000/report/index.html

**Comment by cessen** [comment]
Author of Ropey here.  Please note, in no way am I trying to push Ropey's usage here.  I just find the discussion interesting, and wanted to toss in a couple thoughts.

I don't think the tradeoff between gap buffers and ropes is really about file size.  At small file sizes *anything* will work.  You could just use a plain contiguous string if you wanted, and it would be totally fine.  The whole point of using something like a gap buffer or rope or piece table or whatever is to avoid the shortcomings of something like a contiguous string as files get larger.

Gap buffers are actually *great* for large files, as long as the editing patterns are favorable.  Specifically, for localized edits gap buffers are O(1), which is *amazing*.  And for single-cursor editors, localized edits are pretty much the only case that needs to be handled interactively.  So gap buffers are great (even with huge files) for such editors.  However, gap buffers degrade to O(N) as edits get less and less localized.  So if you want your editor to support non-localized editing patterns, gap buffers probably aren't great.

Ropes make a different performance trade-off, being a sort of "jack of all trades".  They're not *amazing* at anything, but they're always solidly *good* with O(log N) performance.  They're not the best choice for an editor that only supports local editing patterns, since they leave a lot of performance on the table compared to gap buffers in that case (again, even for huge documents).  But for an editor that encourages non-localized edits, or just wants flexibility in that regard, they're a great choice because they always have *good* performance, whereas gap buffers degrade poorly with unfavorable editing patterns.

In other words, regardless of file size, gap buffers have both a better best case and worse worst case compared to ropes.*

It's worth noting, however, that even multiple cursors are frequently quite localized.  Most of the time I use them, for example, all cursors are still in view (or nearly so).  It's really only with editors that are built around multiple cursors as *the* way to edit things that you commonly do interactive non-local edits.

So for something like emacs, I suspect any real arguments in favor of ropes or piece tables (or whatever else) aren't going to be about editing performance, but rather are going to be about secondary features like cheaply taking "snapshots" of a document to save it asynchronously, etc.

\* <i>(Well... in practice many ropes have large leaf nodes--Ropey's are between 512 and 1024 bytes, for example.  So you do need to get to at least a few kilobytes or so before that's true in practice.  But you also have to get even larger than that before using a contiguous string would be a problem, so that's not really the scale where any of this is relevant anyway.)</i>

**Comment by harryfei** [comment]
Do anyone have idea how can we integrate `tree sitter`?

**Comment by CeleritasCelery** [comment]
Why not just use the package?

https://emacs-tree-sitter.github.io/

**Comment by shaunsingh** [comment]
IMO treesitter (and anything else that can be shipped as a standalone package) should be left that way.

**Comment by ReggieMarr** [comment]
IMHO decoupling scrolling from the lisp machine and potentially using ropey would be high value items. I currently find that when opening multiple large files (particularily on large monitors) emacs just can't cope (as in i/o starts lagging considerably).

I'd be willing to assist in this effort however I'm not entirely sure where to start.
