### ISSUE TITLE
Suggestion: merge upstream in a regular schedule

### ISSUE THREAD

**Issue by VitalyAnkh** [emacs-ng/emacs-ng#421]
Since the last merged upstream commit from emacs master branch is `6ebe8b03d8` (Aug 24 2021), it's almost three months gone. Are there any plans to come up with the upstream emacs? Should there be a schedule to do this?
Anyway, keeping up with the upstream is good for the whole community and can also reduce bugs.

**Comment by brotzeit** [comment]
> and can also reduce bugs.

But it can also introduce bugs. Just recently somebody opened a bug at one of my elisp packages and it turned out it's an issue of emacs master.

Nevertheless I do agree that it makes sense to perform upstream merges every month. I already planned to make another merge the next days. However I'm not sure if it's important to have a schedule. But if somebody is motivated to do a merge every first of the month, I won't complain =)

**Comment by brotzeit** [comment]
I just thought about doing the merge but I was reminded of an issue https://github.com/brotzeit/rustic/issues/312. I don't want to merge this bug into emacs-ng. I'm not 100% sure it's an issue of emacs master, but I think we should be sure before the merge.

**Comment by azahid89** [comment]
Waiting patiently for next down merge.
