### ISSUE TITLE
Emacs-ng crashes under Arch Linux

### ISSUE THREAD

**Issue by stefanhusmann** [emacs-ng/emacs-ng#467]
**Describe the bug**
Emacs-ng crashes under Arch Linux.

**To Reproduce**
Steps to reproduce the behavior. What were the options you passed to configure?

```shell
./configure CFLAGS="-Wl,-rpath,shared -Wl,--disable-new-dtags" \
        --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var \
        --with-json --with-modules --with-harfbuzz --with-compress-install \
        --with-threads --with-included-regex --with-zlib --with-cairo --with-libsystemd \
        --with-rsvg --with-native-compilation --with-webrender --without-sound \
	--without-imagemagick --with-gpm --with-dbus --without-pop --without-mailutils \
	--without-gsettings --with-all --disable-build-details
        
```

**Expected behavior**
Emacs should start

**OS**
Which os do you use? (`uname -a`)
Linux frege 6.1.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 06 Feb 2023 09:28:04 +0000 x86_64 GNU/Linux

**Error callstack**
[backtrace.txt](https://github.com/emacs-ng/emacs-ng/files/10724305/backtrace.txt)

**Comment by 2e0byo** [comment]
What happens with [my very hacky fork](https://github.com/2e0byo/emacs-ng/tree/composite-font) ?

This uses glutin rather than surfman, which wouldn't work for me.

I intend to rewrite against the new upstream, probably this weekend.

**Comment by declantsien** [comment]
Hey @stefanhusmann .
Thanks for reporting back.

I think you are running Emacs Webrender in X11 while did not build it with x11 support.
I made webrender x11 an opt-in under flag `--enable-webrender-x11`.

Force running emacs in xwayland using: 
`WINIT_UNIX_BACKEND=x11 ./emacs`
Force running emacs in wayland using:
`WINIT_UNIX_BACKEND=x11 ./emacs`

I will add a message saying that Emacs Webrender did not compiled with X11, instead of crashing out.

**Comment by declantsien** [comment]
@stefanhusmann Can you rebuild your aur against the master branch? And you can reopen if this issue persists.
