### ISSUE TITLE
Winit/WR scaling code is broken

### ISSUE THREAD

**Issue by declantsien** [emacs-ng/emacs-ng#493]
Issue created based on [comment](https://github.com/emacs-ng/emacs-ng/issues/488#issuecomment-1445407191)

> the scaling code is broken, but it always was with winit. (Causes some weird bug with the cursor as clearly two different values for scale are being used internally.)

It should be specific when using winit as windowing implementation.

**Comment by 2e0byo** [comment]
to clarify, emacs doesn't handle scale changed events at all, except by chance if it's forced to redraw the whole window.  winit on my platform incorrectly reports 1.0 as the scale factor when the window loads, but then returns 2.0 a tad later.  Internally we get the scale factor from a variety of sources, sometimes from the window, sometimes from the primary_display (?!).  These clearly contradict, so things jump around on the screen until the scale is correct.

Tao gets the scale right to start with, so this bug is masked.

Separately, the scaling code is backwards.  I think we should be handing logical dimensions to emacs and only using the physical dimensions when rendering.  That way we wouldn't have to *multiply* by the scaling factor to get mouse events in the right place.  Intuitively this should give emacs a smaller screen and save it some work.
