### ISSUE TITLE
s-expression syntax for JavaScript?

### ISSUE THREAD

**Issue by bard** [emacs-ng/emacs-ng#78]
Despite being way more fluent in JavaScript, I always look forward to writing Lisp in Emacs simply because it's such fun. So when I found out about this project, I was immediatley reminded of [eslisp](https://github.com/anko/eslisp), which bills itself as an _un-opinionated S-expression syntax and macro system for JavaScript_.

I was wondering whether there had been any thought in the direction of using JavaScript/TypeScript with a syntax (and what that syntax makes possible) closer to Lisp?

**Comment by yyoncho** [comment]
This: https://github.com/jashkenas/coffeescript/wiki/List-of-languages-that-compile-to-JS 
And this: https://github.com/emacs-ng/emacs-ng/issues/38

**Comment by DavidDeSimone** [comment]
To expand on that further, just because some of the core discussion has happened in our gitter, using JavaScript with a lisp syntax is something the core maintainers are very interested in. Right now, the Lisp virtual machine (VM) is the authoritative VM, and JavaScript works underneath its framework. We believe there will be strong performance gains if we invert that situation - JS is the dominant layer, and existing elisp is transpiled to JS "under the hood".

There are some technical challenges to this approach we are still discussing and working through. In the mean time, if users would like to use transpiled languages like the one linked, or something like ClosureScript, they shouldn't have any issues by just following their build procedure and importing the transpiled JavaScript. (including calling regular lisp functions via the normal means in JS).

**Comment by bard** [comment]
Thanks both for entertaining my musings. :)

> This: https://github.com/jashkenas/coffeescript/wiki/List-of-languages-that-compile-to-JS
> And this: #38

I meant specifically in the context of this project. I'm aware of the list, but that's general, and I had seen #38, but that's about compiling elisp. My thought was about writing JavaScript in JavaScript, except a different syntax. 

_Potential_ upsides (I'm just toying with ideas, the likelihood of them amounting to anything are one in a hundred—optimistically) are that the syntax might be more welcome by existing users (easier to pick up, more fun, not giving up macros), and it might have a chance to reduce the surface impedance mismatch between the two contexts, e.g.:

```js
function foo() {
  lisp.add_hook(lisp.symbols.text_mode_hook, () => {
    lisp.setq(lisp.symbols.foo, "3");
  });
}
```

Could turn into something like:

```lisp
(function foo ()
   (with-elisp
     (add-hook 'text-mode-hook (lambda () (setq foo 3)))))
```

**Comment by yyoncho** [comment]
If the suggestion is to invent lisp closer to JS syntax, IMHO better not do it but pick one of the existing ones that compile to JS. We could create facilities in emacs-ng which would allow using it interactively.

**Comment by bard** [comment]
Ivan Yonchovski <notifications@github.com> writes:

> If the suggestion is to invent lisp closer to JS syntax,

No, not suggesting to invent anything here, just wondering if, by switching from
JavaScript _syntax_ for JavaScript to a lispy _syntax_ for JavaScript
(such as the one provided by [eslisp](https://github.com/anko/eslisp)),
some doors might open.

**Comment by ubolonton** [comment]
The first thing I thought of when seeing Deno-in-Emacs is ClojureScript, but then I realized its compiler is still Clojure (JVM)...

**Comment by DavidDeSimone** [comment]
I'm going to mark this as closed via https://github.com/emacs-ng/emacs-ng/issues/153 , since we have shown you can use ClojureScript within emacs-ng

**Comment by bard** [comment]
Nothing against closing it, but please note that this was about using
"s-expression syntax _for JavaScript_", not using "any language with
s-expression syntax that can compile to JavaScript". ClojureScript is an
example of the latter. An example of the former is the already mentioned
eslisp.

The difference is that an s-expression syntax for JavaScript would not
introduce a third language, and might allow Emacs-ng be extended in its
primary language without giving up things like macros.

>
