### ISSUE TITLE
Decide which melpa packages should be included by default

### ISSUE THREAD

**Issue by yyoncho** [emacs-ng/emacs-ng#98]
Current suggestions 

- use-package
- straight 

Potential candidates:

- magit 
- evil-mode
- projectile 
- flycheck
- company
- ivy + helm

Reference: melpa packages by downloads: https://melpa.org/#/?sort=downloads&asc=false

**Comment by DavidDeSimone** [comment]
I think we should be careful on not including too much, but I think there is serious value in adding some additional base packages.

+1 for straight and magit

**Comment by brotzeit** [comment]
@DavidDeSimone if we include straight we should also add use-package. I also agree on including magit. But IMO that's enough.

**Comment by petr-tik** [comment]
My votes are for straight, magit and evil. 

since emacs-ng is based on emacs master/native-comp, it might be worth using core project.el instead of projectile (projectile is quite a heavy dependency). The main drawback might be the reliance of other packages on projectile, which may be alleviated with aliasing. 

Don't know if this is a good place to ask, please redirect me elsewhere if not. from my perusal of the code, it looks like some LSP client functionality is already integrated in rust. neovim's inclusion of a native LSP client is one of the reason its popularity took off so quickly imo.

**Comment by brotzeit** [comment]
> it looks like some LSP client functionality is already integrated in rust

Yeah that was one of the initial goals. It's currently just stuck at the moment. Maybe we should add an issue to track the progress.

**Comment by brotzeit** [comment]
> My votes are for straight, magit and evil.

evil is too opionated for my tase.

**Comment by jcs090218** [comment]
> since emacs-ng is based on emacs master/native-comp, it might be worth using core project.el instead of projectile (projectile is quite a heavy dependency). The main drawback might be the reliance of other packages on projectile, which may be alleviated with aliasing.

I agree with @petr-tik, I have used both of these packages and `project.el` is indeed faster and a lot more lightweight.

`use-package` may be an good option.

`flycheck` seems to be better than `flymake` so I think it would be great to have it! :)

I think `helm` is better for people who just started use Emacs. I personally like `ivy` since it's faster and more lightweight once people are getting better at elisp.

---

My votes are `flycheck`, `use-package`, `ivy`, `project.el`.

**Comment by brotzeit** [comment]
I would like to not force too many packages on the user especially when there are widely used alternatives.

**Comment by kidd** [comment]
I gave a shot to that, and there are a couple of things I wanted to check with you.

1. should we put those 'extra' packages in a separate directory? something like `/lisp/ng/use-package/`, /lisp/ng/straight/`?
2. these packages need some preprocessing before being fully installable (for example, use-package has a doc subdir which has elisp files we don't need in emacs proper (or they don't even compile due to extra deps).   Is there a 'standard' way to deal with those kind of things? or I should try to be creative about it? 

Thanks!

**Comment by DavidDeSimone** [comment]
@kidd 

1. I vote for something like `lisp/ng/use-package`.
2. I'll defer to @yyoncho and @brotzeit but I don't think we have a standard established. I'm down for doing anything sane, but like I said I'll defer to the other contributors that have more experience in that realm than I do.

Thanks for the input!

**Comment by kidd** [comment]
when including both use-package and straight.el, the only issue I found is the one I sent a PR to, in use-package. If they merge it, we can have this pretty easily. just adding both submodules, and it just works automagically!

No PR yet, as it doesn't make sense until the use-package PR is merged.

**Comment by brotzeit** [comment]
> Is there a 'standard' way to deal with those kind of things? or I should try to be creative about it?

We didn't add elisp packages yet so we don't have a standard. I have no idea how to solve the ox-hugo issue  besides getting your PR merged. I guess we would have to be creative without these changes ?

**Comment by brotzeit** [comment]
Can you do me a favor and add a note to the issues you intend to work on.

**Comment by kidd** [comment]
let's cross fingers and wait for the PR to be merged :)

**Comment by black7375** [comment]
The use-package will be officially emacs included soon.
https://github.com/jwiegley/use-package/issues/282

**Comment by Delanii** [comment]
> @DavidDeSimone if we include straight we should also add use-package. I also agree on including magit. But IMO that's enough.

I have same opinion as @brotzeit , point being to only include `use-package` and `straight`, maybe only `use-package`. I like to use doom emacs and I like to use this distribution to deal with package installation and configuration. And first thing it does is installing straight. Would there be total certainty that `straight` included in emacs-ng wouldnt interfere with that?

**Comment by brotzeit** [comment]
> Would there be total certainty that straight included in emacs-ng wouldnt interfere with that?

That's something we have to ensure. In the worst case we would have to open a pull request for doom-emacs to add a check if straight is already present.

**Comment by declanqian** [comment]
Hey, how about decouple the lisp files from upstream. With minimal
amount lisps to power Emacs up and running. Let straight.el handle packages at user end.

Some lisp from emacs-mirror can be added using straight.el as packages when user needs it.
For example:

```
(use-package dns
  :straight (:type git
             :files ("lisp/net/dns.el")
             :host github
             :repo "emacs-mirror/emacs"))
```

- This way we can have a cleaner source tree, don't need to worry too much about upstream
lisp changes. Easier to maintain?
- Reduce built time when developing, (especially when native-comp enabled). Less to carry?
- There are a lot of lisp files(functions) installed which I never used nor realized. Some
of them are redundant (like the IRC clients / buffer-menu vs ibuffer ...)
- Also the org, I would always fetch the latest using straight...

What do you guys think?

**Comment by declanqian** [comment]
I've integrated straight.el in [my local build](https://github.com/declanqian/emacs/commit/b35f1e05f2374d8a4d658b16863a9c13f77600fb). Replaced `package.el` with `straight.el`, cause I don't want duplicated features. 
Don't think we need to include `use-package` or any other packages. Use `straight.el` to manage packages.
I've made `straight.el` [auto install `use-package`](https://github.com/raxod502/straight.el/pull/810) if `straight-enable-use-package-integration` is non-Nil

**Comment by kidd** [comment]
+1 for adding straight.el. I havent' used it myself but I've only heard good things about it.

We don't want to remove `package.el` because emacs-ng tries to be an additive layer on top of GNU emacs, for both maintainability and featurewise, but if they don't interfere, it should be ok to have both

**Comment by brotzeit** [comment]
> Replaced package.el with straight.el, cause I don't want duplicated features.

As @kidd mentioned, we've had negative experiences with removing code from emacs. As long emacs-ng is based on emacs, I think it's the better way.

> Don't think we need to include use-package or any other packages.

AFAIK use-package is going to be merged into emacs, so it will be present anyway.

**Comment by declanqian** [comment]
Thanks for clarifying that.

Yeah, no problem. I've been poking around Emacs source code/build system.
So far I have some knowledge regrading how (re)build process works.
It's OK for me now not removing code.

Also, +1 for `use-package` and `straight.el`.

**Comment by brotzeit** [comment]
I think we settled for straight. However I think it makes sense to add additional packages if we can leverage them with functionality from emacs-ng(e.g. magit).
